# In case you need to exclude files or directories you can use the `exclude` option
# exclude:
#   - "node_modules"
#   - "packages"
#   - "package.json"
#   - "package-lock.json"

# In case you want to bundle your less/scss define a single entry point
# style:
#   entry: "main.scss"