# In case you need to exclude directories you can use the `exclude` option
# exclude:
#   - "node_modules/"
#   - "packages/"

# In case you want to bundle your less/scss define a single entry point
# style:
#  entry: "main.scss"